/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CentralTeamMatchups {
	headToHead?: MatchupList;
	teamA?: MatchupList;
	teamB?: MatchupList;
}
export interface MatchupList {
	tournaments: {
		id: string;
		name: string;
		start_time: string;
		stages: {
			id: string;
			name: string;
			no_teams: number;
			matches: {
				id: string;
				alpha_id: string;
				bravo_id: string;
				alpha_name: string;
				bravo_name: string;
				alpha_win: number;
				bravo_win: number;
				ties: number;
				[k: string]: unknown;
			}[];
			team_placements: {
				tournament_team_id: string;
				team_id: string;
				set_wins: number;
				sets_played: number;
				placement: number;
				[k: string]: unknown;
			}[];
			[k: string]: unknown;
		}[];
		[k: string]: unknown;
	}[];
	[k: string]: unknown;
}
