/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CentralTeamMatchups {
	headToHead?: MatchupList;
	teamA?: MatchupList;
	teamB?: MatchupList;
}
export interface MatchupList {
	tournaments: {
		id: string;
		name: string;
		stages: {
			id: string;
			name: string;
			matches: {
				id: string;
				alpha_id: string;
				bravo_id: string;
				alpha_name: string;
				bravo_name: string;
				alpha_win: number;
				bravo_win: number;
				ties: number;
			}[];
		}[];
	}[];
}
