name: CI

on:
  push:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  lint-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets['GITHUB_TOKEN'] }}
          ref: ${{ github.ref }}
          fetch-depth: 0
          path: ./sj-overlays

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./sj-overlays/package-lock.json

      - name: Install NPM dependencies
        working-directory: ./sj-overlays
        run: npm ci
        env:
          GSAP_AUTH: ${{ secrets.GSAP_AUTH }}

      - name: Run ESLint on source
        working-directory: ./sj-overlays
        run: npm run lint

      - name: Set up GitHub for SSH access
        if: github.ref == 'refs/heads/master'
        uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets['GH_SSH'] }}

      - name: Set git config
        if: github.ref == 'refs/heads/master'
        working-directory: ./sj-overlays
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Merge master branch into build branch
        if: github.ref == 'refs/heads/master'
        continue-on-error: true
        working-directory: ./sj-overlays
        run: |
          git checkout master
          git checkout build
          git merge master

      - name: Build
        if: github.ref == 'refs/heads/master'
        working-directory: ./sj-overlays
        run: |
          npm run clean
          npm run build

      - name: Commit built files
        if: github.ref == 'refs/heads/master'
        id: commit
        continue-on-error: true
        working-directory: ./sj-overlays
        run: |
          git add -f graphics
          git commit -m "Build result from master branch" -a

      - name: Push built files to "build" branch
        if: github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets['GITHUB_TOKEN'] }}
          branch: build
          directory: ./sj-overlays

  docker-image:
    runs-on: ubuntu-latest
    needs:
      - lint-deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
